services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgsql:/var/lib/postgresql/data
      - pgsql:/var/lib/postgresql/log

  nocodb:
    container_name: nocodb
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - nocodb:/var/lib/nocodb/data

volumes:
  pgsql:
  nocodb:
