version: '3'

vars:
  repo: github.com/shirooe/gomf

tasks:
  protoc:
    desc: Generate Go code from .proto files
    cmds:
      - protoc libs/api/**/*.proto --proto_path=.
        --go_out=. --go_opt=module={{.repo}}
        --go-grpc_out=. --go-grpc_opt=module={{.repo}}
  lint:
    cmd: golangci-lint run ./... -c .golangci.yml